name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'a cheerful greeting'
        required: true
        default: 'Hello'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ inputs.greeting }}"